# Generated by Django 3.2.8 on 2021-11-07 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Имя')),
                ('surname', models.CharField(max_length=127, verbose_name='Фамилия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Уборщица',
                'verbose_name_plural': 'Уборщицы',
            },
        ),
        migrations.CreateModel(
            name='TypeOfNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_number', models.CharField(max_length=127, verbose_name='Тип Номера')),
            ],
            options={
                'verbose_name': 'Тип Номера',
                'verbose_name_plural': 'Типы Номеров',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название Номера')),
                ('number', models.IntegerField(verbose_name='Номер комнаты')),
                ('about', models.TextField(blank=True, verbose_name='Описание номера')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('rent_pay', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Стоимость за ночь')),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hostelrent.cleaner', verbose_name='Уборщица')),
                ('type_of_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hostelrent.typeofnumber', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата вьезда')),
                ('date_of_daparture', models.DateField(verbose_name='Дата выезда')),
                ('total_cost', models.IntegerField(blank=True, null=True, verbose_name='Суммарна стоимость')),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hostelrent.room', verbose_name='Комната')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
